function OAS_RICH(position) {
if (position == 'Top') {
document.write ('<script>\n');
document.write ('var urlBannerSWF = ');
document.write ("'");
document.write ('http://www.mercadolibre.com.ar/org-img/advertising//agenciaclick/sky/sky_vendas_ML_ros_superbanner_pack50porcento_081229.swf');
document.write ("'");
document.write (';\n');
document.write ('var urlBannerGIF = ');
document.write ("'");
document.write ('http://www.mercadolibre.com.ar/org-img/advertising//agenciaclick/sky/sky_vendas_ML_ros_superbanner_pack50porcento_081229.gif');
document.write ("'");
document.write (';\n');
document.write ('var urlAuditIMP = ');
document.write ("'");
document.write ('');
document.write ("'");
document.write (';\n');
document.write ('var urlAuditClick = ');
document.write ("'");
document.write ('http://ad.adnetwork.com.br/mfa/go/img/;s=502;c=2535;a=1;l=1;p=20;sc=17953;n=0;b=73481');
document.write ("'");
document.write (';\n');
document.write ('var AuditCPA = ');
document.write ("'");
document.write ('');
document.write ("'");
document.write (';\n');
document.write ('\n');
document.write ('// medidas\n');
document.write ('var width = ');
document.write ("'");
document.write ('728');
document.write ("'");
document.write (';\n');
document.write ('var height = ');
document.write ("'");
document.write ('90');
document.write ("'");
document.write (';\n');
document.write ('\n');
document.write ('// Tipo de Creativo marcar 1 solo con la letra ');
document.write ("'");
document.write ('x');
document.write ("'");
document.write (' (minuscula)\n');
document.write ('var Flash = ');
document.write ("'");
document.write ('x');
document.write ("'");
document.write (';\n');
document.write ('var Flash_Exp = ');
document.write ("'");
document.write ('');
document.write ("'");
document.write (';\n');
document.write ('var Flash_Multi =');
document.write ("'");
document.write ('');
document.write ("'");
document.write (';\n');
document.write ('var Layer = ');
document.write ("'");
document.write ('');
document.write ("'");
document.write (';\n');
document.write ('var PopUp =');
document.write ("'");
document.write ('');
document.write ("'");
document.write (';\n');
document.write ('var PopUnder =');
document.write ("'");
document.write ('');
document.write ("'");
document.write (';\n');
document.write ('\n');
document.write ('// si es Layer le ponemos el tiempo \n');
document.write (' var time = ');
document.write ("'");
document.write ('5000');
document.write ("'");
document.write (';\n');
document.write ('\n');
document.write ('//si es multilink poner cuantos tiene\n');
document.write ('var LINKS =');
document.write ("'");
document.write ('CAMBIAME');
document.write ("'");
document.write (';\n');
document.write ('var CREATIVO= "CAMBIAME";\n');
document.write ('\n');
document.write ('// si es expandible\n');
document.write ('var widthExpand = "CAMBIAME";\n');
document.write ('var heightExpand = "CAMBIAME";\n');
document.write ('var marginLeft = "0";\n');
document.write ('\n');
document.write ('// No modificar nada\n');
document.write ('var clickTag = ');
document.write ("'");
document.write ('clickTag');
document.write ("'");
document.write (';\n');
document.write ('var adServer = "http://oas.adservingml.com";\n');
document.write ('var PAGE = "ML_BRASIL/ITM/1051/1055/49638";\n');
document.write ('var RAND = "827137484";\n');
document.write ('var POS = "Top";\n');
document.write ('var CAMP = "mercadolibre/MLB_0902_sky_728_ros";\n');
document.write ('var IMAGE = "MLB_0902_sky_728_ros_50pc.html";\n');
document.write ('var USER = "63393162396437633439613161383230";\n');
document.write ('var TARGET = "_blank";\n');
document.write ('var Flash_WMODE="transparent";\n');
document.write ('\n');
document.write ('document.write("<scr" + "ipt src=');
document.write ("'");
document.write ('http://www.mercadolibre.com/org-img/advertising/JMA-RM/JMA-RM-0.3.js');
document.write ("'");
document.write ('>" + "</scr" + "ipt>");\n');
document.write ('</script>');
}
if (position == 'Right3') {
document.write ('<A HREF="http://oas.adservingml.com/RealMedia/ads/click_lx.ads/ML_BRASIL/ITM/1051/1055/49638/1540433005/Right3/default/empty.gif/63393162396437633439613161383230" target="_top"><IMG SRC="http://oas.adservingml.com/RealMedia/ads/Creatives/default/empty.gif"  WIDTH=2 HEIGHT=2 ALT="" BORDER=0 BORDER="0"></A>');
}
}
