# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-29 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(verbose_name=b'Quantidade'),
        ),
    ]
